name: Deploy GitHub Pages

on:
    push:
        branches:
            - main # Remplace par la branche que tu veux suivre pour le déploiement

jobs:
    deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: write # Donne les permissions d'écriture pour le dépôt

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
              with:
                  ref: main # Remplace par ta branche, ex : "production"

            - uses: pnpm/action-setup@v4

            # - name: Set up Node.js
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: "20" # Choisis la version de Node.js requise par ton projet

            - name: Install dependencies
              run: pnpm install

            - name: Build the project
              run: pnpm run build

            - name: Check build output 1
              run: ls -al .

            - name: Check build output 2
              run: ls -al ./apps

            - name: Check build output 3
              run: ls -al ./apps/webfolio

            - name: Check build output 4
              run: ls -al ./apps/webfolio/dist

            - name: Check build output 5
              run: ls -al ./apps/webfolio/dist/spa
            # - name: Deploy to GitHub Pages
            #   uses: peaceiris/actions-gh-pages@v3
            #   with:
            #       github_token: ${{ secrets.GITHUB_TOKEN }}
            #       publish_dir: ../apps/webfolio/dist/spa # Remplace par le répertoire de build de ton projet
